### ISSUE TITLE
Proof-read a printed version of RenoirST chapter

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#47]

**Comment by gcotelli** [comment]
Can I help with this one? What is the process? Should I read the pdf of the chapter and report here if it's ok or create a pull-request if some changes are needed?

**Comment by cdlm** [comment]
A pull request is best for simple fixes like typos, missing words, grammar… you can also look for paragraphs that are too long and should be split, or individual sentences that should be grouped into a paragraphs (I've seen some of those in places, and it breaks the rhythm)

For changes where there is not an obvious solution, either make a separate commit with your proposition so that we ca cherry-pick it, or comment here to start the discussion. This could be for the general organisation of the chapter, or if a paragraph does not make sense, or if a point is not explained, for example.

**Comment by DamienCassou** [comment]
Thanks @gcotelli

**Comment by gcotelli** [comment]
I've create a pull request with some updates and a first review

**Comment by gcotelli** [comment]
Closed by previous commit
