### ISSUE TITLE
Fix the website

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#52]
Some links don't work anymore

**Comment by DamienCassou** [comment]
Broken:
- Read the book online (both options in the drop-down)
- 'as a free printable PDF download.'

Also:
- all chapter links point to outdated chapters

**Comment by dmitrizagidulin** [comment]
One other website-related issue: That page needs some basic SEO (search engine optimization). 
Meaning, when I do a google search for 'Enterprise Pharo', the page http://files.pharo.org/books/enterprisepharo/ does not appear in the first three pages of search results.

For example:

1. The Pharo Books page (which is http://files.pharo.org/books/ ) is not linked directly from Pharo.org/documentation. Instead, the Documentation page links to http://books.pharo.org/ which then redirects to http://files.pharo.org/books/ - not very confidence-inspiring, from the perspective of a search engine. The ideal solution would be to link to the Books page, and also directly to at least the first three books in the series, (U)PBE, [Deep into Pharo](http://deepintopharo.com/), and [Enterprise Pharo](http://files.pharo.org/books/enterprisepharo/).

2. Even better, why not get Square Bracket Associates to register an actual domain for Enterprise Pharo, since the other two books have their own pages?

3. Most importantly (as a short term fix), use the actual name 'Enterprise Pharo' in the two *links* from the Pharo Books page. That is, change the text on the 'View Details' button to 'Enterprise Pharo', and add a title/label to the cover link to refer to the actual title. As it stands, google has no way of knowing that either one of those links actually refer to 'enterprise pharo'.

**Comment by DamienCassou** [comment]
We must remove the links to Zinc-Rest chapter as well

**Comment by DamienCassou** [comment]
I fixed everything except @dmitrizagidulin comments 1 and 2.
