### ISSUE TITLE
Arrows to indicate results in scripts are all different

### ISSUE THREAD

**Issue by DamienCassou** [SquareBracketAssociates/EnterprisePharo#79]
I've seen `->`, `-->`, `=>` and `==>`. Which one do we choose?

**Comment by cdlm** [comment]
I'd avoid -> since it's a common operator, and maybe => for the same reason.

Another solution would be a comment "returns: 42" or "prints: hello world"

On 22 March 2016 at 13:10, Damien Cassou <notifications@github.com> wrote:

> I've seen ->, -->, => and ==>. Which one do we choose?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SquareBracketAssociates/EnterprisePharo/issues/79>
>



-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet
